export const black = 'black'
export const white = 'white'
export const bishop = 'bishop'
export const king = 'king'
export const knight = 'knight'
export const pawn = 'pawn'
export const queen = 'queen'
export const rook = 'rook'